"""Add cancer_screening exercise_comment columns

Revision ID: ef0000fbb21d
Revises: f8f972d2c860
Create Date: 2024-09-28 15:08:55.498812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0000fbb21d'
down_revision: Union[str, None] = 'f8f972d2c860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_info', sa.Column('cancer_screening', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_info', 'cancer_screening')
    # ### end Alembic commands ###
