"""Add diet_comment exercise_comment columns

Revision ID: f8f972d2c860
Revises: e8a162cad8b8
Create Date: 2024-09-10 15:59:08.168741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f972d2c860'
down_revision: Union[str, None] = 'e8a162cad8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_info', sa.Column('diet_comment', sa.String(), nullable=True))
    op.add_column('patient_info', sa.Column('exercise_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_info', 'exercise_comment')
    op.drop_column('patient_info', 'diet_comment')
    # ### end Alembic commands ###
